use MIST353A3
go
--Jayden Donham start
insert into Occupation (Position, Wage)
values
('Doordash Driver', '15'),
('Uber Driver', '25'),
('Trucker', '50');
go

insert into Location (State, City, Zip)
values
('West Virginia', 'Morgantown', '26505'),
('Pennsylvania', 'Pittsburgh', '15106'),
('Ohio', 'Cleveland', '44101');
go
--Jayden Donham end

--Josh Keller
-- Insert data into DRIVER table
-- Mock data, generated by ChatGPT. Prompt in README


INSERT INTO DRIVER (DID, DPosition, D_First, D_Last, D_Hometown, D_LNum) 
VALUES 
(1, 'Flatbed Driver', 'John', 'Smith', 'New York', 'DL12345'),
(2, 'Auto Hauler', 'Emily', 'Johnson', 'Los Angeles', 'DL67890'),
(3, 'Freight Hauler', 'Michael', 'Williams', 'Chicago', 'DL24680'),
(4, 'Delivery Driver', 'Sarah', 'Brown', 'Houston', 'DL13579'),
(5, 'Tanker Driver', 'James', 'Davis', 'Phoenix', 'DL86420'),
(6, 'Courier', 'Jessica', 'Martinez', 'Philadelphia', 'DL97531'),
(7, 'Dump Truck Driver', 'David', 'Anderson', 'San Antonio', 'DL35791'),
(8, 'Long Haul Driver', 'Jennifer', 'Garcia', 'San Diego', 'DL68024'),
(9, 'Bus Driver', 'Robert', 'Rodriguez', 'Dallas', 'DL24681'),
(10, 'School Bus Driver', 'Lisa', 'Lopez', 'San Jose', 'DL24682'),
(11, 'Transit Driver', 'Daniel', 'Wilson', 'Austin', 'DL24683'),
(12, 'Shuttle Driver', 'Megan', 'Hernandez', 'Jacksonville', 'DL24684'),
(13, 'Truck Driver', 'William', 'Walker', 'Indianapolis', 'DL24685'),
(14, 'Forklift Operator', 'Ashley', 'Young', 'San Francisco', 'DL24686'),
(15, 'Lift Truck Operator', 'Christopher', 'King', 'Columbus', 'DL24687'),
(16, 'Van Driver', 'Amanda', 'Scott', 'Charlotte', 'DL24688'),
(17, 'Tow Truck Driver', 'Matthew', 'Green', 'Fort Worth', 'DL24689'),
(18, 'Garbage Truck Driver', 'Samantha', 'Baker', 'Detroit', 'DL24690'),
(19, 'Loader Operator', 'Andrew', 'Hill', 'Seattle', 'DL24691'),
(20, 'Crane Operator', 'Elizabeth', 'Perez', 'Denver', 'DL24692');
GO

-- Insert mock data generated by ChatGPT
-- Prompt in READMME
-- Inserting mock data into POI table

INSERT INTO POI (POI_ID, POI_Name, POI_Add_Num, POI_Street, POI_City, POI_State, POI_ZIP)
VALUES
(1, 'Rest Area 1', 100, 'Highway 1', 'Springfield', 'Illinois', 62701),
(2, 'Truck Stop 24/7', 200, 'Interstate 55', 'Lexington', 'Kentucky', 40502),
(3, 'Travel Plaza', 300, 'Highway 101', 'Bakersfield', 'California', 93301),
(4, 'Rest Haven', 400, 'Interstate 80', 'Omaha', 'Nebraska', 68101),
(5, 'Roadside Oasis', 500, 'Highway 20', 'Boise', 'Idaho', 83701);
GO

--Josh Keller end


--Ryan Sladic start 
-- Inserting 20 rows of data into the AUTOMOTIVE_PARTS table with PDescription and PCategory constraint
--Used chatGTP to generate data for the table)
INSERT INTO AutoPart(PNum, PManu, PCategory, PCountry, PPrice, PDescription)
VALUES 
    (1, 'ABC Manufacturing', 'Mechanical', 'USA', 50, 'Engine'),
    (2, 'XYZ Tech', 'Cosmetic', 'China', 30, 'Headlight'),
    (3, 'Tech Innovators', 'Mechanical', 'Japan', 80, 'Transmission'),
    (4, 'Global Parts', 'Cosmetic', 'Germany', 120, 'Brake'),
    (5, 'MegaCorp', 'Mechanical', 'South Korea', 40, 'Suspension'),
    (6, 'Tech Solutions', 'Cosmetic', 'USA', 60, 'Exhaust'),
    (7, 'TopTech', 'Mechanical', 'China', 90, 'Fuel Pump'),
    (8, 'Global Innovations', 'Cosmetic', 'Germany', 110, 'Battery'),
    (9, 'InnoTech', 'Mechanical', 'Japan', 75, 'Alternator'),
    (10, 'Cosmetic World', 'Cosmetic', 'South Korea', 35, 'Tire'),
    (11, 'FutureTech', 'Mechanical', 'USA', 55, 'Starter'),
    (12, 'MechMasters', 'Mechanical', 'Germany', 95, 'Radiator'),
    (13, 'BeautyTech', 'Cosmetic', 'Japan', 45, 'Air Filter'),
    (14, 'EuroCosmetics', 'Cosmetic', 'France', 65, 'Oil Filter'),
    (15, 'TechGurus', 'Mechanical', 'USA', 85, 'Ignition Coil'),
    (16, 'DynamicParts', 'Mechanical', 'China', 70, 'Shock Absorber'),
    (17, 'EcoCosmetics', 'Cosmetic', 'Netherlands', 55, 'Wiper Blade'),
    (18, 'RoboTech', 'Mechanical', 'Japan', 100, 'Water Pump'),
    (19, 'GlamourTech', 'Cosmetic', 'South Korea', 75, 'Head Gasket'),
    (20, 'InnoParts', 'Mechanical', 'Germany', 120, 'Oxygen Sensor');


--Inserting data into VEHICLE table 
-- Inserting data into the VEHICLE table
--Used chatGTP to generate data for the table)
INSERT INTO VEHICLE (VIN, VMake, VModel, VYear)
VALUES 
    (1234567, 'Toyota', 'Camry', 2022),
    (2345678, 'Honda', 'Civic', 2021),
    (3456789, 'Ford', 'Escape', 2023),
    (4567890, 'Chevrolet', 'Malibu', 2022),
    (5678901, 'Nissan', 'Altima', 2021),
    (6789012, 'Hyundai', 'Sonata', 2023),
    (7890123, 'BMW', '3 Series', 2022),
    (8901234, 'Mercedes-Benz', 'C-Class', 2021),
    (9012345, 'Audi', 'A4', 2023),
    (1234501, 'Lexus', 'ES', 2022),
    (2345012, 'Subaru', 'Outback', 2023),
    (3450123, 'Mazda', 'CX-5', 2022),
    (4501234, 'Kia', 'Sorento', 2021),
    (5012345, 'Volkswagen', 'Tiguan', 2023),
    (6123450, 'Tesla', 'Model Y', 2022),
    (7234501, 'Ford', 'F-150', 2021),
    (8345012, 'Chevrolet', 'Silverado', 2023),
    (9450123, 'Ram', '1500', 2022),
    (1561234, 'Toyota', 'Tacoma', 2021),
    (2672345, 'Nissan', 'Frontier', 2023);

-- End Ryan Sladic 
